
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','branza cu mucegai, specialitate de branza tare, mix branzeturi(cascaval + mozzarella), sos, brie, aluat','Quatro Formaggi',34.99,'https://speisekarte.menu/storage/media/dishes_main/2220568/conversions/dish_thumbnail.jpg',1);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','ardei gras, ciuperci, salam vară, sunca de porc, mix branzetur (cascaval + mozzarella), sos, aluat','Quattro Stagioni',36.99,'https://d2j6dbq0eux0bg.cloudfront.net/images/16648100/1678550920.jpg',1);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','chifla cu susan, 4 x vita tocata, 4 x cheddar, ceapa, rosii, mix salata, castraveti murati, mayoneza cu usturoi, sos cocktail | 600g','UPPERCUT',38.99,'https://carulcuburgeri.ro/wp-content/uploads/2020/05/carulcuburgeri-produs-5-300x300.jpg',2);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','chiflă cu mac și susan, salată coleslaw, sos de maioneză cu usturoi, sos cocktail, file din piept de pui crispy, roșii | 350g','CHICKEN ROYALE',29.99,'https://carulcuburgeri.ro/wp-content/uploads/2020/05/carulcuburgeri-produs-9-600x600.jpg',2);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','smântână, spaghetti, kaiser, specialitate de branza tare','Carbonara',26.99,'https://www.bucataras.ro/uploads/modules/news/68092/656x440_spaghete-carbonara-363543.jpg',3);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','mix branzeturi (cascaval + mozzarella), sos, aluat','Margherita',25.44,'https://d16bcxkz31d65o.cloudfront.net/800x533/v2/Foto%202016/Pizza/2020%20v2/margherita.jpg',1);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','chifla cu susan, vita tocata, ceapa, rosii, castraveti murati, mix de salata, mayoneza cu usturoi, sos cocktail | 280g','CLASIC BEEF',21.5,'https://carulcuburgeri.ro/wp-content/uploads/2020/05/carulcuburgeri-produs-1-600x600.jpg',2);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','chifla cu susan, vita tocata, ceapa, rosii, castraveti murati, mix de salata, mayoneza cu usturoi, sos cocktail | 280g','CLASIC BEEF',22,'https://carulcuburgeri.ro/wp-content/uploads/2020/05/carulcuburgeri-produs-1-600x600.jpg',2);
INSERT INTO food_online_shop.food (`currency`,`description`,`name`,`price`,`thumbnail`,`food_category_id`) VALUES ('RON','chifla cu susan, vita tocata, ceapa, rosii, castraveti murati, mix de salata, mayoneza cu usturoi, sos cocktail | 280g','CLASIC BEEF',61,'https://carulcuburgeri.ro/wp-content/uploads/2020/05/carulcuburgeri-produs-1-600x600.jpg',2);
